### ISSUE TITLE
Salut Liviu!

### ISSUE THREAD

**Issue by zadannu** [ionesculiviucristian/eoncms#2]
Am pus si eu pe github pana la urma .Ce mai faci ?

**Comment by ionesculiviucristian** [comment]
Plm... Let's grab a beer :))

Sent from Yahoo Mail on Android

**Comment by ionesculiviucristian** [comment]
Let's have a beer sometime man... :))

**Comment by ionesculiviucristian** [comment]
F**k :))

**Comment by zadannu** [comment]
I can drink just non alcohoolic beer.So i'm fucked.

**Comment by ionesculiviucristian** [comment]
Let me do tbe rest :))

Sent from Yahoo Mail on Android

**Comment by zadannu** [comment]
Halt and catch fire rullz.

**Comment by ionesculiviucristian** [comment]
Yes :))

Sent from Yahoo Mail on Android
